function addtag(a,c){var b=document.getElementById("txtE"),e=document.getElementById("linkUrl").value,f=document.getElementById("linkUrlTag").value,d=a;1==c?(d='<a href="'+a+'" target="_blank" title="'+a+'"><img src="'+a+'"/>',subtag="</a>"):"a"==a?(d='<a target="_blank" rel="nofollow"',subtag="</a>"):"at"==a?(d='<a target="_blank" rel="nofollow"',subtag="</a>"):"img"==a?(d="<img ",subtag="</img>"):"code"==a?(d='<pre><code onclick="fSelCode(this)" >',subtag="</code></pre>"):(d="<"+d+">",subtag="</"+
a+">");document.selection?(b.focus(),sel=document.selection.createRange(),sel.text="code"==a?d+sel.text.replace(/</g,"&lt;")+subtag:"at"==a?d+' href="'+f+sel.text+'/" title="'+sel.text+'" />'+sel.text+subtag:"a"==a?d+' href="'+e+sel.text+'/" title="'+sel.text+'" />'+sel.text+subtag:"img"==a?d+' src="'+sel.text+'/" alt="'+sel.text+'" />'+subtag:d+sel.text+subtag):b.selectionStart||"0"==b.selectionStart?(strSelected=b.value.substring(b.selectionStart,b.selectionEnd),b.value="at"==a?b.value.substring(0,
b.selectionStart)+d+' href="'+f+strSelected+'/"  title="'+strSelected+'">'+strSelected+""+subtag+b.value.substring(b.selectionEnd,b.textLength):"a"==a?b.value.substring(0,b.selectionStart)+d+' href="'+e+strSelected+'/"  title="'+strSelected+'">'+strSelected+""+subtag+b.value.substring(b.selectionEnd,b.textLength):"img"==a?b.value.substring(0,b.selectionStart)+d+' src="'+strSelected+'"  alt="'+strSelected+'">'+subtag+b.value.substring(b.selectionEnd,b.textLength):b.value.substring(0,b.selectionStart)+
d+strSelected+subtag+b.value.substring(b.selectionEnd,b.textLength)):b.value=d+subtag;feChange(0)}function strip_tags(a,c){c=(((c||"")+"").toLowerCase().match(/<[a-z][a-z0-9]*>/g)||[]).join("");return a.replace(/\x3c!--[\s\S]*?--\x3e|<\?(?:php)?[\s\S]*?\?>/gi,"").replace(/<\/?([a-z][a-z0-9]*)\b[^>]*>/gi,function(a,e){return-1<c.indexOf("<"+e.toLowerCase()+">")?a:"&lt"+e.toLowerCase()+"&gt"})}var isCtrl=!1,isAlt=!1;
function feChange(a){var c;c=document.getElementById("txtE").value;c=c.replace(/\n/g,"<br//>");c=strip_tags(c,"<br><b><i><u><strike><s><a><img><iframe><div><code><h1><h2><h3><pre>");document.getElementById("e").innerHTML=c;isCtrl=!1;17==a.which&&(isCtrl=!1);isAlt=!1;18==a.which&&(isAlt=!1);feSel();fCount()}
function keyDownTextarea(a){17==a.which&&(isCtrl=!0);18==a.which&&(isAlt=!0);1==isCtrl&&0==isAlt&&(66==a.which?(a.preventDefault(),addtag("b",0)):73==a.which?(a.preventDefault(),addtag("i",0)):85==a.which?(a.preventDefault(),addtag("u",0)):83==a.which?(a.preventDefault(),addtag("s",0)):49==a.which?(a.preventDefault(),addtag("h1",0)):50==a.which?(a.preventDefault(),addtag("h2",0)):51==a.which?(a.preventDefault(),addtag("h3",0)):65==a.which?(a.preventDefault(),addtag("a",0)):77==a.which?(a.preventDefault(),
addtag("img",0)):81==a.which?(a.preventDefault(),addtag("code",0)):71==a.which&&(a.preventDefault(),addtag("at",0)))}function feChange2(a){a=document.getElementById("e").innerText;a=a.replace(/\n/g,"<br//>");a=strip_tags(a,"<br><b><i><u><strike><s><a><img><iframe><div><code><h3><pre>");document.getElementById("e").innerHTML=a}
function feChangeW(a){var c,b="";c=document.getElementById("w").value;a=document.getElementById("u");wArray=c.split(" ");for(c=0;c<wArray.length;c++)3<wArray[c].length&&(b+=wArray[c].replace(/([.*+?^=!:${}()\u00bf\u00a1|\[\]\/\\])/g,"")+",");b=b.substring(0,b.length-1);a.value=b}function fConfirmDelete(a,c,b){document.getElementById(a).innerHTML="";document.getElementById("dc"+c).innerHTML='<a href="'+b+'">\u00bfSeguro que quieres eliminarlo?</a>'}
function feSel(){var a=document.getElementById("txtE");q="";document.selection?(a.focus(),sel=document.selection.createRange(),q=sel.text):q=a.value.substring(a.selectionStart,a.selectionEnd);-1!=q.indexOf(".")&&(document.getElementById("linkUrl").value=q)}
function fEdit(a,c,b,e,f,d){var g,h,k;g=document.getElementById(e);e=document.getElementById("submit");h=document.getElementById("txtE");k=document.getElementById("answer");1==c?document.getElementById("d").checked=!0:document.getElementById("d").checked=!1;1==a?document.getElementById("f").checked=!0:document.getElementById("f").checked=!1;"Cancelar"!=g.innerHTML?(g.innerHTML="Cancelar",a=document.getElementById("sec"+f).innerHTML,a=a.replace(/(<p>|<\/p>)/g,""),a=a.replace(/\n/g,""),a=a.replace(/<br>/g,
"\n"),h.value=a,k.action=d,0==f?(a=document.getElementById("h2Title").innerHTML,f=document.getElementById("w"),f.style.display="block",f.value=a,f=document.getElementById("u"),f.style.display="block",f.value=b,b=document.getElementById("blopin"),b.style.display="block"):(b=document.getElementById("blopin"),b.style.display="none"),e.value="Terminar edici\u00f3n",window.scrollTo(0,document.body.scrollHeight)):(d=d.replace("q=5","q=2"),k.action=d,g.innerHTML="Editar el mensaje",e.value="Responder",h.value=
"");feChange()}function fSelCode(a){if(document.selection){var c=document.body.createTextRange();c.moveToElementText(a);c.select()}else window.getSelection&&(c=document.createRange(),c.selectNode(a),window.getSelection().addRange(c))}function fCount(){var a,c;a=document.getElementById("txtE");c=document.getElementById("dvCont");a=a.value.split(" ").length+a.value.split("\n").length;0<a&&200>a?c.innerHTML=a+" palabras.":199<a&&(c.innerHTML=a+" palabras. Este mensaje te dar\u00e1 2 puntos")}
function fSearch0(a,c,b){13==a.which&&fSearch(c,b)}function fSearch(a,c){var b="",e;e=encodeURIComponent(document.getElementById("googleSearch").value);0==a&&(b="https://www.google.com/?#q="+e+"+site:"+encodeURIComponent(c)+"");window.open(b,"_blank")}function fCookieAdv(a,c){window.open(c+"?c=1&r="+a)};