function addtag(a,b){var c=document.getElementById("txtE"),e=document.getElementById("linkUrl").value,g=document.getElementById("linkUrlTag").value,f=a.substring(a.lastIndexOf("/")+1);1!=b&&2!=b&&3!=b||!document.getElementById("poimg")||(document.getElementById("poimg").value=a);var d=a;1==b?(d='<a href="'+a+'" target="_blank" title="'+f+'"><img class="imgUploadText"  src="'+a+'"/>',subtag="</a>"):2==b?(d='<video class="videoUploadText" src="'+a+'" controls>Tag video not supported',subtag="</video>"):
3==b?(d='<a href="'+a+'" target="_blank" title="Download '+f+'"><b><u>'+f+"</u></b>(\u2193)",subtag="</a>"):"a"==a?(d='<a target="_blank" rel="nofollow"',subtag="</a>"):"at"==a?(d='<a target="_blank" rel="nofollow"',subtag="</a>"):"img"==a?(d="<img ",subtag="</img>"):"video"==a?(d="<video ",subtag="</video>"):"code"==a?(d='<pre><code onclick="fSelCode(this)" >',subtag="</code></pre>"):(d="<"+d+">",subtag="</"+a+">");document.selection?(c.focus(),sel=document.selection.createRange(),sel.text="code"==
a?d+sel.text.replace(/</g,"&lt;")+subtag:"at"==a?d+' href="'+g+sel.text+'/" title="'+sel.text+'" />'+sel.text+subtag:"a"==a?d+' href="'+e+'" title="'+sel.text+'" />'+sel.text+subtag:"img"==a?d+' class="imgUploadText" src="'+sel.text+'/" alt="'+sel.text+'" />'+subtag:"video"==a?d+' class="videoUploadText" src="'+sel.text+'/" controls>Tag video not supported'+subtag:d+sel.text+subtag):c.selectionStart||"0"==c.selectionStart?(strSelected=c.value.substring(c.selectionStart,c.selectionEnd),strSelected=
strSelected.replace(/^\s\s*/,"").replace(/\s\s*$/,""),strSelectedLinkTag=strSelected.replace(/ /g,"-"),"code"==a&&(strSelected=strSelected.replace(/</g,"&lt;")),c.value="at"==a?c.value.substring(0,c.selectionStart)+d+' href="'+g+strSelectedLinkTag+'/"  title="'+strSelected+'">'+strSelected+""+subtag+c.value.substring(c.selectionEnd,c.textLength):"a"==a?c.value.substring(0,c.selectionStart)+d+' href="'+e+'"  title="'+strSelected+'">'+strSelected+""+subtag+c.value.substring(c.selectionEnd,c.textLength):
"img"==a?c.value.substring(0,c.selectionStart)+d+' class="imgUploadText" src="'+strSelected+'"  alt="'+strSelected+'">'+subtag+c.value.substring(c.selectionEnd,c.textLength):"video"==a?c.value.substring(0,c.selectionStart)+d+' class="videoUploadText" src="'+strSelected+'"  controls>Tag video not supported'+subtag+c.value.substring(c.selectionEnd,c.textLength):c.value.substring(0,c.selectionStart)+d+strSelected+subtag+c.value.substring(c.selectionEnd,c.textLength)):c.value=d+subtag;feChange(0)}
function strip_tags(a,b){b=(((b||"")+"").toLowerCase().match(/<[a-z][a-z0-9]*>/g)||[]).join("");return a.replace(/\x3c!--[\s\S]*?--\x3e|<\?(?:php)?[\s\S]*?\?>/gi,"").replace(/<\/?([a-z][a-z0-9]*)\b[^>]*>/gi,function(a,e){return-1<b.indexOf("<"+e.toLowerCase()+">")?a:"&lt"+e.toLowerCase()+"&gt"})}var isCtrl=!1,isAlt=!1;
function feChange(a){var b;b=document.getElementById("txtE").value;b=b.replace(/\n/g,"<br//>");b=strip_tags(b,"<br><b><i><u><strike><s><a><img><iframe><div><code><h1><h2><h3><pre><video><adsense>");document.getElementById("e").innerHTML=b;isCtrl=!1;17==a.which&&(isCtrl=!1);isAlt=!1;18==a.which&&(isAlt=!1);feSel();fCount()}
function keyDownTextarea(a){17==a.which&&(isCtrl=!0);18==a.which&&(isAlt=!0);1==isCtrl&&0==isAlt&&(66==a.which?(a.preventDefault(),addtag("b",0)):73==a.which?(a.preventDefault(),addtag("i",0)):85==a.which?(a.preventDefault(),addtag("u",0)):83==a.which?(a.preventDefault(),addtag("s",0)):49==a.which?(a.preventDefault(),addtag("h1",0)):50==a.which?(a.preventDefault(),addtag("h2",0)):51==a.which?(a.preventDefault(),addtag("h3",0)):52==a.which?(a.preventDefault(),addtag("adsense",0)):69==a.which?(a.preventDefault(),
addtag("a",0)):77==a.which?(a.preventDefault(),addtag("img",0)):81==a.which?(a.preventDefault(),addtag("code",0)):71==a.which?(a.preventDefault(),addtag("at",0)):72==a.which&&(a.preventDefault(),addtag("video",0)))}function feChange2(a){a=document.getElementById("e").innerText;a=a.replace(/\n/g,"<br//>");a=strip_tags(a,"<br><b><i><u><strike><s><a><img><iframe><div><code><h3><pre>");document.getElementById("e").innerHTML=a}
function feChangeW(a){var b,c="";b=document.getElementById("w").value;a=document.getElementById("u");wArray=b.split(" ");for(b=0;b<wArray.length;b++)3<wArray[b].length&&(c+=wArray[b].replace(/([.*+?^=!:${}()\u00bf\u00a1|\[\]\/\\])/g,"")+",");c=c.substring(0,c.length-1);a.value=c}function fConfirmDelete(a,b,c){c=c.replace(/"/g,"%22");document.getElementById(a).innerHTML="";document.getElementById("dc"+b).innerHTML='<a href="'+c+'">\u00bfSeguro que quieres eliminarlo?</a>'}
function feSel(){var a=document.getElementById("txtE");q="";document.selection?(a.focus(),sel=document.selection.createRange(),q=sel.text):q=a.value.substring(a.selectionStart,a.selectionEnd);-1!=q.indexOf(".")&&(-1==q.indexOf("//")?document.getElementById("linkUrl").value="http://"+q:document.getElementById("linkUrl").value=q)}
function fEdit(a,b,c,e,g,f,d){var h,k;h=document.getElementById(g);a=document.getElementById("submit");g=document.getElementById("txtE");k=document.getElementById("answer");1==c?document.getElementById("d").checked=!0:document.getElementById("d").checked=!1;1==b?document.getElementById("f").checked=!0:document.getElementById("f").checked=!1;"Cancelar"!=h.innerHTML?(h.innerHTML="Cancelar",b=document.getElementById("sec"+f).innerHTML,b=b.replace(/(<p>|<\/p>)/g,""),b=b.replace(/\n/g,""),b=b.replace(/<br>/g,
"\n"),g.value=b,k.action=d,0==f?(f=document.getElementById("u"),f.style.display="block",f.value=e,e=document.getElementById("blopin"),e.style.display="block"):(e=document.getElementById("blopin"),e.style.display="none"),a.value="Terminar edici\u00f3n",window.scrollTo(0,document.body.scrollHeight)):(d=d.replace("q=5","q=2"),k.action=d,h.innerHTML="Editar el mensaje",a.value="Responder",g.value="");feChange()}
function fSelCode(a){if(document.selection){var b=document.body.createTextRange();b.moveToElementText(a);b.select()}else window.getSelection&&(b=document.createRange(),b.selectNode(a),window.getSelection().addRange(b))}function fCount(){var a,b;a=document.getElementById("txtE");b=document.getElementById("dvCont");a=a.value.split(" ").length+a.value.split("\n").length;0<a&&200>a?b.innerHTML=a+" palabras.":199<a&&(b.innerHTML=a+" palabras. Este mensaje te dar\u00e1 2 puntos")}
function fSearch0(a,b,c){13==a.which&&fSearch(b,c)}function fSearch(a,b){var c="",e;e=encodeURIComponent(document.getElementById("googleSearch").value);0==a&&(c="https://www.google.com/?#q="+e+"+site:"+encodeURIComponent(b)+"");window.open(c,"_blank")}function fCookieAdv(a,b){window.open(b+"?c=1&r="+a)};